name: Auto Clock In

on:
  # push 到 main 分支的时候会触发打卡，我会检测重复打卡的
  push:
    branches:
      - main
  # 定时打卡
  schedule:
    # 下方代码第一段数字表示第 10 分钟和第20分钟，第二段数字表示 23 小时，但是这个时间比北京时间晚 8 小时，所以当前打卡的时间为每天 7 点 10 分和7 点 20 分，打卡两次避免遇到错误打卡失败，放心，脚本会检查重复打卡。请不要把时间设置在 3 点到 6 点，此时学校服务器会关闭。不过定时执行一般会延迟接近一个小时，没办法，免费版要排队。
    - cron: 10,20 23 * * *
    
env:
  PUSH_KEY: ${{ secrets.PUSH_KEY }}
  OPEN_ID: ${{ secrets.OPEN_ID }}
  STUDENT_NUM: ${{ secrets.STUDENT_NUM }}
  ADDRESS: ${{ secrets.ADDRESS }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: yarn
              
            - name: Run Script
              run: node index.js
