name: Auto Clock In

on:
  # push 到 main 分支的时候会触发打卡，我会检测重复打卡的
  push:
    branches:
      - main
  # 定时打卡
  schedule:
    # 建议改一下打卡时间，下方代码第一个数字表示 10 分钟，第二个数字表示 23 小时，但是这个时间比北京时间晚 8 小时，所以当前打卡的时间为每天 7 点 42
    - cron: 50 23 * * *
    
env:
  PUSH_KEY: ${{ secrets.PUSH_KEY }}
  OPEN_ID: ${{ secrets.OPEN_ID }}
  MRDK_KEY: ${{ secrets.MRDK_KEY }}
  STUDENT_NUM: ${{ secrets.STUDENT_NUM }}
  ADDRESS: ${{ secrets.ADDRESS }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: yarn
              
            - name: Run Script
              run: node index.js
